#!/bin/sh
umask '0002'
etckeeper commit -m 'Auto commit before applying cluster config.'
etckeeper vcs pull origin auto-conf -X theirs -s recursive --no-edit
etckeeper init
/usr/lib/plan9/bin/mk -f /etc/cluster/mkfile `hostname` || /usr/lib/plan9/bin/mk -f /etc/cluster/mkfile
etckeeper init
etckeeper commit -m 'Auto commit after applying cluster config.'
