#!/bin/bash
umask '0022'
s6-setlock -w /var/lib/cluster/lock true || {
	echo "configurador is already running."
	exit 1
}
etckeeper commit -m 'Auto commit before applying cluster config.'
etckeeper vcs pull origin auto-conf -X theirs -s recursive --no-edit
etckeeper init
/usr/lib/plan9/bin/mk -f /etc/cluster/mkfile `hostname` || /usr/lib/plan9/bin/mk -f /etc/cluster/mkfile
etckeeper init
etckeeper commit -m 'Auto commit after applying cluster config.'
