#!/usr/bin/awk -f

$0 ~ /^[^#]/ \
&& is_ip($1) \
&& $1 != "0.0.0.0" \
&& !self_host($1) && !self_host($2) {
	IP=$1
	{print "=" $2 ":" IP}
	for(i=3; i<=NF; i++) {
		{print "+" $i ":" IP}
	}
}

function is_ip(str) {
	if (str ~ /(1?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.(1?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.(1?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.(1?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])/) {
		return 1 #true
	} else {
		return 0 #false
	}
}

function self_host(str) {
	if (str ~ /local/ || str ~ /^127\./) {
		return 1 #true
	} else {
		return 0 #false
	}
}
