#!/bin/sh
RAMA="$1"
umask 0002
etckeeper commit -m "Antes de probar rama $RAMA"
etckeeper vcs reset --hard
etckeeper vcs pull origin $RAMA -X theirs -s recursive --no-edit
etckeeper init
/etc/cron.hourly/configurador
etckeeper commit -m "Después de probar rama $RAMA"
