dummy:V:	montar_fs	htc_computo	renombrar_git
	echo "nothing to do"

# Hosts
visnu:V:	compartir_fs
notron:V:	compartir_fs	htc_computo
fai:V:	paquetes_computo
arenero:V:	htc_submit

# clases
compartir_fs:V:	/var/lib/cluster/compartido
montar_fs:V:	/var/lib/cluster/montar_fs
htc_computo:V:	/var/lib/cluster/htc_computo	paquetes_computo
htc_submit:V:	/var/lib/cluster/htc_submit	paquetes_computo
paquetes_computo:V:	/var/lib/cluster/paquetes_computo
renombrar_git:V:	/var/lib/cluster/renombrar_git

/var/lib/cluster/renombrar_git:
	etckeeper vcs branch -m `hostname` \
	&& mkdir -p `dirname $target` \
	&& touch $target

/var/lib/cluster/paquetes_computo:	/etc/cluster/paquetes_computo
	mkdir -p `dirname $target`
	apt-get -y install `cat $prereq` \
	&& touch $target

/var/lib/cluster/compartido:	/etc/exports
	set -x
	etckeeper commit -m 'Generar configuración para compartir sistemas de archivos' || true \
	&& etckeeper vcs push \
	&& mkdir -p `dirname $target` \
	&& touch /var/lib/cluster/compartido

/etc/exports:	/etc/cluster/nfs_exports
	set -x
	apt-get -y install nfs-kernel-server
	grep -E '^'`hostname`':' $prereq \
	| sed -e 's#^'`hostname`':##' \
	> $target

/var/lib/cluster/montar_fs:	/etc/cluster/nfs_mounts
	set -x
	apt-get -y install nfs-common
	cat $prereq \
	| grep -vE '^'`hostname`':' \
	| xargs -l -I{} \
		sh -c 'grep "{}" /etc/fstab || echo "{}" >> /etc/fstab'
	awk '{print $2}' $prereq | xargs mkdir -p
	mount -a
	etckeeper commit -m 'Sistemas de archivos compartidos.' || true
	etckeeper vcs push
	mkdir -p `dirname $target`
	touch $target
